version: "3"
services:
  spark-master:
    image: bde2020/spark-master:2.2.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  helloworld:
    image: disco-spark-helloworld:0.1.0-SNAPSHOT
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "INPUT_DIR=file:///tmp/helloworld"
