version: "3"
services:
  spark-master:
    image: bde2020/spark-master:2.2.1-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    depends_on:
      - hdfs-namenode
    env_file:
      - ./hadoop.env
    ports:
      - "50075:50075"

  helloworld:
    image: disco-spark-helloworld:0.1.0-SNAPSHOT
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "INPUT_DIR=hdfs://hdfs-namenode/world/"
      - "OUTPUT_DIR=hdfs://hdfs-namenode/helloworld/"
